
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={role:"student",user:null};
const toast=(msg)=>{const t=$("#toast");t.textContent=msg;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2600)};
function setTheme(mode){localStorage.setItem("ems_theme",mode);document.body.classList.toggle("dark",mode==="dark"||(mode==="auto"&&matchMedia("(prefers-color-scheme: dark)").matches));}
setTheme(localStorage.getItem("ems_theme")||"auto");
function openLogin(){ $("#loginModal").classList.add("show"); }
function closeLogin(){ $("#loginModal").classList.remove("show"); }
["openLogin","heroLogin","aboutLogin","mobileLogin"].forEach(id=>{const e=$("#"+id);if(e)e.onclick=openLogin});
$("#closeLogin").onclick=closeLogin;$(".modal-backdrop").onclick=closeLogin;
$$("[data-scroll]").forEach(b=>b.onclick=()=>$( "#"+b.dataset.scroll).scrollIntoView({behavior:"smooth"}));
$$(".theme-picker button").forEach(b=>b.onclick=()=>setTheme(b.dataset.theme));
$("#themeBtn").onclick=()=>{const m=localStorage.getItem("ems_theme")||"auto";setTheme(m==="light"?"dark":m==="dark"?"auto":"light")};
$("#dashTheme").onclick=()=>{const m=localStorage.getItem("ems_theme")||"auto";setTheme(m==="light"?"dark":m==="dark"?"auto":"light")};
$$(".form-tabs button").forEach(b=>b.onclick=()=>{ $$(".form-tabs button").forEach(x=>x.classList.remove("active"));b.classList.add("active");$("#loginForm").classList.toggle("hidden",b.dataset.form!=="login");$("#signupForm").classList.toggle("hidden",b.dataset.form!=="signup");});
$$(".role").forEach(b=>b.onclick=()=>{$$(".role").forEach(x=>x.classList.remove("active"));b.classList.add("active");state.role=b.dataset.role});
$("#togglePass").onclick=()=>{$("#loginPass").type=$("#loginPass").type==="password"?"text":"password";$("#togglePass").textContent=$("#loginPass").type==="password"?"Show":"Hide"};
async function api(path,opts={}){const r=await fetch(path,{headers:{"Content-Type":"application/json"},...opts});const d=await r.json();if(!r.ok)throw new Error(d.error||"Request failed");return d}
$("#loginSubmit").onclick=async()=>{const msg=$("#loginMsg");msg.textContent="";try{const d=await api("/api/login",{method:"POST",body:JSON.stringify({username:$("#loginUser").value,password:$("#loginPass").value})});state.user=d.user;closeLogin();await loadDashboard();toast("Welcome to EMS, "+d.user.name+"!");}catch(e){msg.textContent=e.message;msg.style.color="#b34d4d"}};
$("#signupSubmit").onclick=async()=>{const msg=$("#signupMsg");msg.textContent="";try{const d=await api("/api/signup",{method:"POST",body:JSON.stringify({role:$("#signupRole").value,name:$("#signupName").value,username:$("#signupUser").value,password:$("#signupPass").value,className:$("#signupClass").value,section:$("#signupSection").value})});msg.style.color="#5f8b68";msg.textContent=d.message;if(!d.pending){$("#loginUser").value=$("#signupUser").value;$$(".form-tabs button")[0].click();}}catch(e){msg.textContent=e.message;msg.style.color="#b34d4d"}};
$("#closeStudentModal").onclick=()=>$("#studentModal").classList.remove("show");$("#studentModal .modal-backdrop").onclick=()=>$("#studentModal").classList.remove("show");$("#saveStudent").onclick=saveStudent;
$("#logout").onclick=async()=>{await api("/api/logout",{method:"POST"});state.user=null;$("#app").classList.add("hidden");$("#landing").classList.remove("hidden");$(".site-header").classList.remove("hidden");window.scrollTo({top:0,behavior:"smooth"});toast("Logged out safely.")};
$("#backSite").onclick=()=>{$("#app").classList.add("hidden");$("#landing").classList.remove("hidden");$(".site-header").classList.remove("hidden")};
function side(role){const items=role==="student"?["Overview","Results","Attendance","Progress","Notices","AI Tutor"]:["Overview","Students","Results","Attendance","Notices","AI Tutor","Approvals"];$("#sideNav").innerHTML=items.map((x,i)=>`<button class="side-item ${i===0?"active":""}" data-side="${x}">${x}</button>`).join("");$$(".side-item").forEach(x=>x.onclick=()=>{ $$(".side-item").forEach(y=>y.classList.remove("active"));x.classList.add("active");if(x.dataset.side==="AI Tutor")renderAI();});
}
function metric(label,val,sub=""){return `<div class="metric"><span>${label}</span><b>${val}</b><small>${sub}</small></div>`}
function renderStudent(d){const s=d.student;$("#dashContent").innerHTML=`<div class="dash-title">Good to see you, ${s.name.split(" ")[0]}.</div><p class="dash-sub">Class ${s.className||"—"}${s.section?" • Section "+s.section:""} · Student ID ${s.studentId}</p><div class="metric-grid">${metric("Overall result",s.overall+"%","Current performance")}${metric("Attendance",s.attendance+"%","Healthy attendance")}${metric("Class rank","#"+s.rank,"Current position")}${metric("Subjects",(s.subjects||[]).length,"Tracked subjects")}</div><div class="dash-grid"><div class="panel"><h3>Subject performance</h3>${(s.subjects||[]).map(x=>`<div class="subject"><div class="subject-top"><span>${x.name}</span><b>${x.marks}%</b></div><div class="bar"><i style="width:${x.marks}%"></i></div></div>`).join("")||"<p class='muted'>Your teacher has not entered subject results yet.</p>"}</div><div><div class="panel"><h3>Focus area</h3><div class="focus-box">${weak(s)}<br><br>Keep practising 20–30 minutes daily and ask the AI Tutor whenever you get stuck.</div></div><div class="panel" style="margin-top:15px"><h3>Latest notices</h3>${d.notices.slice(0,3).map(n=>notice(n)).join("")}</div></div></div><div class="panel" style="margin-top:15px"><h3>AI Tutor</h3><div class="ai"><input id="aiQ" placeholder="Ask: Explain Newton's 3rd law simply..."><button id="aiAsk">Ask AI</button></div><div id="aiA" class="muted" style="margin-top:12px"></div></div>`;$("#aiAsk").onclick=askAI}
function weak(s){const a=(s.subjects||[]).filter(x=>x.marks<80).sort((a,b)=>a.marks-b.marks);return a.length?`<b>Needs attention:</b> ${a[0].name} (${a[0].marks}%)`:"<b>Great work!</b> No subject is currently below 80%."}
function notice(n){return `<div class="notice"><b>${n.title}</b><p>${n.text}</p><small>${n.date}</small></div>`}
function renderStaff(d){const canEdit=["teacher","coordinator","principal","admin"].includes(state.user.role);const canAdd=["coordinator","principal","admin"].includes(state.user.role);$("#dashContent").innerHTML=`<div class="dash-title">${state.user.role[0].toUpperCase()+state.user.role.slice(1)} workspace</div><p class="dash-sub">Manage the information your role is authorised to access.</p><div class="metric-grid">${metric("Students",d.students.length,"Records")}${metric("Teachers",(d.teachers||[]).length,"Staff records")}${metric("Notices",d.notices.length,"Published")}${metric("Role",state.user.role.toUpperCase(),"Access level")}</div>${canAdd?`<div class="staff-actions"><button class="primary" id="addStudentBtn">＋ Add Student</button><button class="ghost" id="importCsvBtn">⇧ Import CSV</button><input id="csvFile" type="file" accept=".csv,text/csv" hidden></div>`:""}<div class="dash-grid"><div class="panel"><h3>Student records</h3><table class="table"><thead><tr><th>Name</th><th>Class</th><th>Result</th><th>Attendance</th><th></th></tr></thead><tbody>${d.students.map(s=>`<tr><td>${s.name}</td><td>${s.className}-${s.section}</td><td>${s.overall}%</td><td>${s.attendance}%</td><td>${canEdit?`<button class="edit-btn" onclick='editStudent(${JSON.stringify(s)})'>Edit</button>`:"View only"}</td></tr>`).join("")}</tbody></table></div><div><div class="panel"><h3>Publish notice</h3><label class="muted">Title<input id="noticeTitle" class="dash-input"></label><label class="muted">Message<textarea id="noticeText" class="dash-input" rows="4"></textarea></label><button class="primary wide" id="publishNotice">Publish</button></div><div class="panel" style="margin-top:15px"><h3>Recent notices</h3>${d.notices.slice(0,4).map(notice).join("")}</div></div></div>`;$("#publishNotice").onclick=publishNotice;if(canAdd){$("#addStudentBtn").onclick=()=>{$("#studentModal").classList.add("show");};$("#importCsvBtn").onclick=()=>$("#csvFile").click();$("#csvFile").onchange=importCSV;}}
window.editStudent=async s=>{const att=prompt("Attendance %",s.attendance);if(att===null)return;const overall=prompt("Overall result %",s.overall);if(overall===null)return;await api("/api/students/"+s.id,{method:"PUT",body:JSON.stringify({attendance:Number(att),overall:Number(overall),subjects:s.subjects})});toast("Student record updated.");loadDashboard()};
async function publishNotice(){try{await api("/api/notices",{method:"POST",body:JSON.stringify({title:$("#noticeTitle").value,text:$("#noticeText").value})});toast("Notice published.");loadDashboard()}catch(e){toast(e.message)}}
async function saveStudent(){const msg=$("#studentMsg");msg.textContent="";try{const d=await api("/api/students",{method:"POST",body:JSON.stringify({name:$("#stName").value,fatherName:$("#stFather").value,className:$("#stClass").value,section:$("#stSection").value,studentId:$("#stId").value,username:$("#stUsername").value,password:$("#stPassword").value})});msg.style.color="#5f8b68";msg.textContent=d.message;toast("Student added successfully.");setTimeout(()=>{$("#studentModal").classList.remove("show");loadDashboard()},500)}catch(e){msg.style.color="#b34d4d";msg.textContent=e.message}}
async function importCSV(ev){const file=ev.target.files[0];if(!file)return;const text=await file.text();const lines=text.split(/\r?\n/).filter(Boolean);if(lines.length<2){toast("CSV needs a header and at least one student.");return}const parse=l=>l.split(",").map(x=>x.trim().replace(/^\"|\"$/g,""));const h=parse(lines[0]);const rows=lines.slice(1).map(l=>{const a=parse(l),o={};h.forEach((k,i)=>o[k]=a[i]||"");return o});try{const d=await api("/api/students/import",{method:"POST",body:JSON.stringify({rows})});toast(d.message+(d.errors?.length?` ${d.errors.length} row(s) skipped.`:""));loadDashboard()}catch(e){toast(e.message)}ev.target.value=""}
async function askAI(){const q=$("#aiQ").value;if(!q)return;$("#aiA").textContent="Thinking…";try{const d=await api("/api/ai",{method:"POST",body:JSON.stringify({question:q})});$("#aiA").textContent=d.answer}catch(e){$("#aiA").textContent=e.message}}
function renderAI(){$("#dashContent").innerHTML=`<div class="dash-title">AI Tutor</div><p class="dash-sub">Ask a school question and get a simple explanation.</p><div class="panel"><div class="ai"><input id="aiQ" placeholder="What do you not understand?"><button id="aiAsk">Ask AI</button></div><div id="aiA" class="muted" style="margin-top:20px"></div><div style="margin-top:20px"><button class="ghost" onclick='$("#aiQ").value="Explain Newton 3rd law simply";$("#aiAsk").click()'>Newton's 3rd law</button> <button class="ghost" onclick='$("#aiQ").value="What is photosynthesis?";$("#aiAsk").click()'>Photosynthesis</button> <button class="ghost" onclick='$("#aiQ").value="What is DNA?";$("#aiAsk").click()'>DNA</button></div></div>`;$("#aiAsk").onclick=askAI}
async function loadDashboard(){const d=await api("/api/dashboard");$("#landing").classList.add("hidden");$(".site-header").classList.add("hidden");$("#app").classList.remove("hidden");state.user=d.user;$("#sideName").textContent=d.user.name;$("#sideRole").textContent=d.user.role;$("#sideAvatar").textContent=d.user.name[0].toUpperCase();side(d.user.role);if(d.user.role==="student")renderStudent(d);else renderStaff(d)}
(async()=>{try{const d=await api("/api/me");if(d.user){state.user=d.user;await loadDashboard()}}catch{};setTimeout(()=>{$$(".reveal").forEach((x,i)=>{setTimeout(()=>x.classList.add("visible"),i*80)});},3800);})();
window.addEventListener("scroll",()=>{$$(".reveal").forEach(x=>{if(x.getBoundingClientRect().top<innerHeight*.9)x.classList.add("visible")})});


// Footer portal shortcut
const footerLogin = document.getElementById('footerLogin');
if (footerLogin) footerLogin.addEventListener('click', () => document.getElementById('loginModal')?.classList.add('show'));
